8/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_pk>/", views.detail, name="detail"),
    # path("recommended/<int:genre_pk>", views.recommended, name="recommended"),
    path("recommended/", views.recommended, name="recommended"),
    path("genre/<int:genre_id>/", views.GenreDetail, name="GenreDetail"),
]

8/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

8/movies/models.py
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=50)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

8/movies/forms.py
from django import forms

# Create your forms here.

8/movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe
from .models import Movie, Genre
import heapq

API_KEY = "13e149d16bf61eaad0368a40a8a17771"


# Create your views here.
@require_safe
def index(request):
    # 전체 영화 목록 가져오기
    movies = Movie.objects.all()
    context = {"movies": movies}
    print(context)
    return render(request, "movies/index.html", context)


@require_safe
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {
        "movie": movie,
    }
    return render(request, "movies/detail.html", context)


@require_safe
def recommended(request):
    user = request.user
    if user.is_authenticated:
        # 10개 영화 추천
        recommneded_movies_priority_queue = []
        all_genres = set(Genre.objects.all())
        all_movie_ranking = Movie.objects.all().order_by("vote_average")
        all_movie_visited = [False] * len(all_movie_ranking)
        # 1. 좋아요한 영화의 장르 받기
        liked_reviews = user.like_reviews.all()
        print(liked_reviews)
        liked_movie_genres = set()
        for lr in liked_reviews:
            try:
                mv = Movie.objects.get(title=lr.movie_title)
                print(mv)
                gnrs = mv.genres.all()
                for gnr in gnrs:
                    liked_movie_genres.add(gnr)
            except:
                print("no matching mv title")
        print(f"liked: {liked_movie_genres}")
        # 2. 각 장르별 영화 추천
        # 3. 각 장르별 별점 기준 추천
        # 4. 각 장르 겹치는 수가 많을수록 먼저 추천
        if len(liked_movie_genres) == 0:
            liked_movie_genres = all_genres
        for idx, mv in enumerate(all_movie_ranking):
            # 해당 mv의 generes.all과 liked_genres와의 우선순위 구하기
            priority = len(liked_movie_genres.intersection(mv.genres.all()))
            if all_movie_visited[idx] == False:
                all_movie_visited[idx] = True
                heapq.heappush(recommneded_movies_priority_queue, (-priority, idx))
        print(recommneded_movies_priority_queue)
        cnt = 0
        recommneded_movies = []
        while cnt < 10:  # 우선순위 큐에서 10개만 뽑기
            popped = heapq.heappop(recommneded_movies_priority_queue)
            recommneded_movies.append(all_movie_ranking[popped[1]])
            cnt += 1
        print(recommneded_movies)
        context = {"recommneded_movies": recommneded_movies}
        return render(request, "movies/recommended.html", context)
    return redirect("moives:index")


@require_safe
def GenreDetail(request, genre_id):
    genre = Genre.objects.get(pk=genre_id)
    movies = genre.movie_set.all()
    context = {
        "movies": movies,
    }
    return render(request, "movies/index.html", context)

8/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{movie.title}}</h1>
<br>
<img src="{{movie.poster_path}}" alt="" width="300">
<div>
    <h4>기본 정보</h4>
    <p>{{movie.title}}</p>
    <p>{{movie.release_date}} 
        {% for genre in movie.genres.all %}
        <a href="{% url 'movies:GenreDetail' genre.pk%}">
            {{genre.name}}
        </a>
        {% endfor %}
    </p>
    <p>{{movie.overview}}</p>
</div>
<hr>
<div>
    <a href="{% url 'movies:index' %}">뒤로가기</a>
</div>
{% endblock %}

{% comment %} title = models.CharField(max_length=100)
release_date = models.DateField()
popularity = models.FloatField()
vote_count = models.IntegerField()
vote_average = models.FloatField()
overview = models.TextField()
poster_path = models.CharField(max_length=200)
genres = models.ManyToManyField(Genre) {% endcomment %}

8/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>
  <hr>
  <a href="{% url 'movies:recommended' %}">영화 추천 받기</a>
  <hr>
  <!-- Movies List -->
  <main role="main" style="padding-top: 72.12px" >
    <div class="album  text-center">
      <div class="container">
        <div class="row">
          
          {% for movie in movies %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" style="display: block;" src="{{movie.poster_path}}" >
              <div class="card-body text-start">
                <h5 class="">
                  <a href="{% url 'movies:detail' movie.pk %}">
                    {{movie.title}}
                  </a> 
                </h5>
                <p class="">
                  {% for genre in movie.genres.all %}
                  <a href="{% url 'movies:GenreDetail' genre.pk %}">
                    {{genre.name}}
                  </a>
                  {% endfor %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>        
          {% endfor %}
        </div>
      </div>
    </div>   
  </main>
{% endblock %}

{% comment %} title = models.CharField(max_length=100)
release_date = models.DateField()
popularity = models.FloatField()
vote_count = models.IntegerField()
vote_average = models.FloatField()
overview = models.TextField()
poster_path = models.CharField(max_length=200)
genres = models.ManyToManyField(Genre) {% endcomment %}

8/movies/templates/movies/recommended.html
{% extends 'base.html' %}
{% block content %}
	<h1>Recommended Movies for {{ user.username }}</h1>
  <hr>
  <main role="main" style="padding-top: 72.12px" >
    <div class="album  text-center">
      <div class="container">
        <div class="row">

          {% for movie in recommneded_movies %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" style="display: block;" src="{{movie.poster_path}}" >
              <div class="card-body text-start">
                <h5 class="">
                  <a href="{% url 'movies:detail' movie.pk %}">
                    {{movie.title}}
                  </a> 
                </h5>
                <p class="">
                  {% for genre in movie.genres.all %}
                    {{genre.name}}
                  {% endfor %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>        
          {% endfor %}

        </div>
      </div>
    </div>   
  </main>
{% endblock %}