6/pjt/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
]

6/pjt/movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.content
    

6/pjt/movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

6/pjt/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET, require_http_methods


@require_GET
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

@require_http_methods(['GET','POST'])
def create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = MovieForm(request.POST)
            if form.is_valid():
                movie = form.save(commit=False)
                movie.user = request.user
                movie.save()
    
                return redirect('movies:detail', movie.pk)
        else:
            form = MovieForm()
        context = {
            'form': form,
        }
        return render(request, 'movies/create.html', context)
    else:
        return redirect('accounts:login')

@require_GET
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie': movie,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'movies/detail.html', context)


@require_http_methods(['GET','POST'])
def update(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        if request.user == movie.user:
            if request.method == 'POST':
                form = MovieForm(request.POST, instance=movie)
                if form.is_valid():
                    form.save()
                return redirect('movies:detail', movie.pk)
            else:
               form = MovieForm(instance=movie)
    
        else:
            return redirect('movies:detail', movie.pk)
        context = {
            'movie': movie,
            'form': form,
        }
        return render(request, 'movies/update.html', context)
    else:
        return redirect('accounts:login')
    

@require_POST
def delete(request, pk):
    print('>>>')
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        if request.user == movie.user:
            movie.delete()
            return redirect('movies:index')
        return redirect('movies:detail', movie.pk)
    else:
        return redirect('accounts:login')

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect('movies:detail', movie.pk)
    
    return redirect('accounts:login')

@require_POST
def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('movies:detail', movie_pk)

@require_POST
def likes(request, pk):
    print('>>>')
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)

        return redirect('movies:index')
    
    return redirect('accounts:login')

6/pjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock %}

6/pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <div>
    <h5>{{ movie.title }}</h5>
    <p>{{ movie.description }}</p>
  </div>

  <a href="{% url 'movies:update' movie.pk %}">수정하기</a>
      <form action="{% url 'movies:delete' movie.pk %}" id="delete-form" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기" id="delete-btn" />
      </form><br>
      <hr>

      <h5>Comments</h5>
      <hr>
      {% if comments %}
        <p><b>{{comments|length}}개의 댓글</b></p>
      {% endif %}
  
      <ul>
        {% for comment in comments %}     
          <li>
            <a href="{% url 'accounts:profile' comment.user.pk %}">{{comment.user}}</a>
            : {{comment.content}} 
            {% if request.user == comment.user %}
            <form action="{% url 'movies:comments_delete' movie.pk comment.pk%}" method="POST">
              {% csrf_token %}
              <input type="submit" value="삭제">
            </form>
            {% endif %}
            {% empty %}
            <li>댓글이 없습니다 :(</li>
          {% endfor %}
          </li>
        </ul>
        {% if request.user.is_authenticated %}
        <form action="{% url 'movies:comments_create' movie.pk %}" method="POST">
          {% csrf_token %}
          {{comment_form}}
          <input type="submit" value="저장">
        </form>
        {% else %}
          <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
        {% endif %}
      </div>

  <a href="{% url 'movies:index' %}">BACK</a>
  <hr>
{% endblock content %}

6/pjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'movies:create' %}">[CREATE]</a>
  <hr>
  {% for movie in movies %}
    <a href="{% url 'movies:detail' movie.pk %}"><p>{{ movie.title }}</p></a>
    {% if request.user.is_authenticated %}
      <form action="{% url 'movies:likes' movie.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in movie.like_users.all %}
          <input type="submit" value="좋아요 취소">
        {% else %}
          <input type="submit" value="좋아요">
        {% endif %}
      </form>
    {% endif %}
    <hr>
  {% endfor %}

{% endblock %}

6/pjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">TITLE</label>
      <input type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div>
      <label for="description">DESCRIPTION</label>
      <textarea id="description" rows="3" name="description">{{ movie.description }}</textarea>
    </div>
    <input type="reset" value="Reset">
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock %}