6/pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('signup/',views.signup, name='signup'),
    path('delete/',views.delete, name='delete'),
    path('update/',views.update, name='update'),
    path('password/',views.change_password, name='change_password'),
    path('profile/<int:pk>/',views.profile, name='profile'),
    path('<int:user_pk>/follow/',views.follow, name='follow'),
]

6/pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    

6/pjt/accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm  
from django.contrib.auth import get_user_model  

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name')

6/pjt/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
#

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import get_user_model

# Create your views here.
@require_http_methods(['GET','POST'])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    
    else:
        form = AuthenticationForm()
    
    context = {
        'form' : form,
    }
    return render(request,'accounts/login.html',context)
    

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET','POST'])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET','POST'])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/update.html', context)


@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET','POST'])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

@login_required
@require_GET
def profile(request, pk):
    User = get_user_model()
    person = User.objects.get(pk=pk)
    context = {
        'person' : person,
    }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        User = get_user_model()
        person = User.objects.get(pk=user_pk)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.pk)
    else:
        return redirect('accounts:login')

6/pjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<!--페이지 명-->
<div>
    <h1>비밀번호 변경</h1>
</div>

<!--비밀번호 수정 폼-->
<div>
    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
</div>

<!--변경취소하고 메인페이지로 돌아가기-->
<div>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>

{% endblock content %}

6/pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
<!--현재 페이지 명-->
<div>
    <h1>Login</h1>
</div>
<!--로그인 폼-->
<div>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
</div>

<!--로그인 취소하고 메인페이지로 돌아가기-->
<div>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>
    
{% endblock content %}

6/pjt/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{person.username}} 님의 프로필</h1>
  <div>
    <div>
        팔로잉 : {{person.followings.all|length}} / 팔로워 : {{person.followers.all|length}}
    </div>
    {% if request.user != person %}
      <div>
        <form action="{% url 'accounts:follow' person.pk %}" method = "POST">
            {% csrf_token %}
            {% if request.user in person.followers.all %}
              <input type="submit" value="Unfollow">
            {% else %}
              <input type="submit" value="Follow">
            {% endif %}
        </form>
      </div>
    {% endif %}
  </div>

  <hr>

  <h2>{{person.username}}'s 게시글</h2>
  {% for movie in person.movie_set.all  %}
    <div>
      <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
    </div>
  {% endfor %}

   
  <h2>{{person.username}}'s 좋아요한 게시글</h2>
  {% for movie in person.like_movies.all %}
    <div>
      <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
    </div>
  {% endfor %}

  <hr>

  <a href="{% url 'movies:index' %}">back</a>
{% endblock content %}

6/pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<!--현재 페이지 명-->
<div>
    <h1>Signup</h1>
</div>

<!--회원가입 폼-->
<div>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
</div>

<!--회원가입 취소하고 메인페이지로 돌아가기-->
<div>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>

{% endblock content %}

6/pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<!--현재 페이지명-->
<div>
    <h1>회원정보수정</h1>
</div>

<!--정보수정 폼-->
<div>
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
</div>

<!--변경취소하고 메인페이지로 돌아가기-->
<div>
    <a href="{% url 'movies:index' %}">돌아가기</a>
</div>


{% endblock content %}